[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "antares-legacy-gems-converter"
version = "0.0.1"
description = "Convert Antares Legacy studies to GEMS format"
license = {text = "MPL-2.0"}
requires-python = ">=3.10"
dependencies = [
    "gemspy",
    "numpy",
    "PyYAML>=6.0",
    "pydantic",
    "antares_craft>=0.3",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "pytest~=7.0.0",
    "pytest-cov",
]


[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["src"]
